database:
  jdbcClass: org.sqlite.JDBC
  connection: jdbc:sqlite
  name: /home/uwe/development/products-mogk.db

csvInput:
  productsFilename: csv/products.csv
  producersFilename: csv/producers.csv
  marketsFilename: csv/markets.csv
  ordersFilename: csv/orders.csv
  orderitemsFilename: csv/orderitems.csv
  productContainersFilename: csv/containers.csv
  productOriginsFilename: csv/origins.csv