extends: default
page:
  layout: portrait
  margin: [1.5cm, 1.5cm, 1.5cm, 1.5cm]
  size: A4
base:
  font_color: #333333
  font_family: Helvetica
  font_size: 9
  line_height_length: 17
  line_height: 1.2
  padding: 2mm
vertical_rhythm: $base_line_height_length
heading:
  font_size: 12
  font_style: bold
  line_height: 1.2
  margin-bottom: 0.3cm
table:
  font_family: Helvetica
  font_size: 9
  cell:
    padding: 3
