database:
  jdbcClass: org.sqlite.JDBC
  connection: jdbc:sqlite
  name: /home/uwe/development/products-mogk.db

sparkJava:
  staticfilesExpiretime: 10
  locale: de
  tempFolder: /tmp

labels:
  glabelsBinary: /usr/bin/glabels-3-batch
  glabelsFile: /home/uwe/development/artikel/glabels/etiketten-01.glabels
  pdfOutputFolder: /home/uwe/development/artikel/glabels/pdf

asciidoc:
  templateFileFolder: /home/uwe/development/artikel/asciidoc
  pdfOutputFolder: /home/uwe/development/artikel/asciidoc/pdf
  themeFile: /home/uwe/development/artikel/asciidoc/asciidoc-theme-1.yml

csvInput:
  filesFolder: /home/uwe/development/csv
  productsFilename: products.csv
  producersFilename: producers.csv
  marketsFilename: markets.csv
  ordersFilename: orders.csv
  orderitemsFilename: orderitems.csv
  productContainersFilename: containers.csv
  productOriginsFilename: origins.csv
  usersFilename: users.csv
