database:
  jdbcClass: org.sqlite.JDBC
  connection: jdbc:sqlite
  name: /home/uwe/development/products-mogk.db

sparkJava:
  staticfilesExpiretime: 10
  locale: de

labels:
  glabelsBinary: /usr/bin/glabels-3-batch
  glabelsFile: /home/uwe/development/mogk-etiketten-01.glabels
  tempFolder: /tmp

csvInput:
  filesFolder: /home/uwe/development/csv
  productsFilename: products.csv
  producersFilename: producers.csv
  marketsFilename: markets.csv
  ordersFilename: orders.csv
  orderitemsFilename: orderitems.csv
  productContainersFilename: containers.csv
  productOriginsFilename: origins.csv
  usersFilename: users.csv
