database:
  jdbcClass: org.sqlite.JDBC
  connection: jdbc:sqlite
  name: products-mogk.db

sparkJava:
  port: 4567
  staticfilesExpiretime: 10
  locale: de
  tempFolder: /tmp
  tokenExpiresMinutes: 180
  documentsFolder: documents
  keystoreFile: <keystore file>
  keystorePassword: <keystore password>

opa:
  host: http://localhost:8181

webApp:
  chartingNumberOfWeeksToDisplay: 10
  recentlyChangedProductsNumberOfDays: 30
  recentlyUnchangedProductsNumberOfDaysMin: 30
  recentlyUnchangedProductsNumberOfDaysMax: 60
  shorttermUnchangedProductsNumberOfDaysMin: 60
  shorttermUnchangedProductsNumberOfDaysMax: 90
  longtermUnchangedProductsNumberOfDaysMin: 90

email:
  templateFileFolder: config
  emailTemplateFilename: email_template_01.vm
  mailTransportProtocol: smtp
  mailSmtpHost: smtp.web.de
  mailSmtpPort: "587"
  mailSender: some.body@mymail.de
  mailSenderPassword: mysecretpassword
  mailFrom: some.body@mymail.de

labels:
  glabelsBinary: /usr/bin/glabels-3-batch
  productLabelsFile: config/etiketten-01.glabels
  pdfOutputFolder: pdf

asciidoc:
  templateFileFolder: config
  pdfOutputFolder: pdf
  themeFile: config/asciidoc-theme-1.yml

csvInput:
  filesFolder: /home/user1/artikel/csv
  productsFilename: products.csv
  producersFilename: producers.csv
  marketsFilename: markets.csv
  ordersFilename: orders.csv
  orderitemsFilename: orderitems.csv
  productContainersFilename: containers.csv
  productOriginsFilename: origins.csv
  usersFilename: users.csv
